### ISSUE TITLE
Server side usage?

### ISSUE THREAD

**Issue by IronOxidizer** [astei/lazydfu#10]
Is it advantageous to run this on my server? Or are the benefits strictly client side?

**Comment by astei** [comment]
Yes, LazyDFU can run client side and server side and has the same benefits (faster server boot times and lower peak CPU usage at start). In fact, LazyDFU was derived from a Paper patch that does the exact thing.

I hope this answers your question.

**Comment by IronOxidizer** [comment]
Yes it does. Thanks for the quick reply!
