### ISSUE TITLE
Less ram allowed

### ISSUE THREAD

**Issue by Lucario4LyfeYT** [astei/lazydfu#11]
When I boot into minecraft, I allocate it 12gb of ram. I did multiple tests with this mod to see if it would lessen the ram allocated, and it did. minecraft only used a maximum of 2gb of ram with lazydfu on, when I took it off it went back up to a max of 12gb ram. Please fix this

For context, minecraft said 12gb of ram was allocated, but wasn't using all the ram I asked it to use. About 20 tests with and without this mod was taken.

This is my first issue thing on this site, hope I did it right

**Comment by astei** [comment]
I have no idea what you're talking about here. I don't work for Mojang, and if I did, there would be no need for this mod as it would have been integrated into vanilla.

**Comment by Lucario4LyfeYT** [comment]
> I have no idea what you're talking about here. I don't work for Mojang, and if I did, there would be no need for this mod as it would have been integrated into vanilla.

I can send a video of what is happening for better clarification because you don't understand what I'm talking about

**Comment by astei** [comment]
> I can send a video of what is happening for better clarification because you don't understand what I'm talking about

DFU does create a lot of garbage when it initializes, but your issue doesn't specify what I need to do. Are you asking me to _increase_ the memory usage of LazyDFU? Your issue is bizarre and so far seems to defy any attempt at explanation.

The only case where this might make sense is looking at the allocated memory at a point in time - but this information is really just noise, and for Minecraft you really want the allocated heap size to be equal to the maximum heap size, and you do that by making `-Xms` and `-Xmx` equal to each other.

**Comment by Lucario4LyfeYT** [comment]
What happens, is, I allow minecraft to use 12gb of ram. Without this mod installed, on average, it usually uses 9gb out of the 12gb I allow it to use. When I use this mod, even by itself, minecraft only uses 2gb of ram instead of what it usually uses. That's the problem. That's the issue.

**Comment by DragonEggBedrockBreaking** [comment]
> What happens, is, I allow minecraft to use 12gb of ram. Without this mod installed, on average, it usually uses 9gb out of the 12gb I allow it to use. When I use this mod, even by itself, minecraft only uses 2gb of ram instead of what it usually uses. That's the problem. That's the issue.

Minecraft using 9gb RAM is by itself concerning, unless you are running a heavy modpack on a high render distance with a lot of contraptions in the world...

**Comment by Lucario4LyfeYT** [comment]
I use max graphics with max render distance, so minecraft using 9gb of ram is ok

**Comment by astei** [comment]
> What happens, is, I allow minecraft to use 12gb of ram. Without this mod installed, on average, it usually uses 9gb out of the 12gb I allow it to use. When I use this mod, even by itself, minecraft only uses 2gb of ram instead of what it usually uses. That's the problem. That's the issue.

So you're complaining that LazyDFU doesn't use _enough memory_? That's a first. I don't think I want to fix that - to me, this sounds like a good thing.

**Comment by DragonEggBedrockBreaking** [comment]
> I use max graphics with max render distance, so minecraft using 9gb of ram is ok

That still shouldn’t be using that much ram, unless you use heavy mod packs and/or extremely high resolution texture packs (e.g. 128x or 256x)

**Comment by Lucario4LyfeYT** [comment]
> > I use max graphics with max render distance, so minecraft using 9gb of ram is ok
> 
> That still shouldn’t be using that much ram, unless you use heavy mod packs and/or extremely high resolution texture packs (e.g. 128x or 256x)

I have 2 screenshots. Both have the f3 menu open. The first one is WITHOUT Lazydfu installed and the second is WITH Lazydfu installed
![LazyDfu NOT INSTALLED](https://user-images.githubusercontent.com/86382621/123339012-70e1bd00-d50f-11eb-924a-00ab5251f0a8.png)
![LazyDfu INSTALLED](https://user-images.githubusercontent.com/86382621/123339020-750dda80-d50f-11eb-9a20-c993f211f7fe.png)

**Comment by DragonEggBedrockBreaking** [comment]
But we still don’t understand the issue, why is less RAM usage a bad thing?

**Comment by Lucario4LyfeYT** [comment]
Because I want minecraft to USE the ram I ALLOW it to USE

**Comment by Lucario4LyfeYT** [comment]
Also stuttering

**Comment by creeper123123321** [comment]
> > > I use max graphics with max render distance, so minecraft using 9gb of ram is ok
> > 
> > 
> > That still shouldn’t be using that much ram, unless you use heavy mod packs and/or extremely high resolution texture packs (e.g. 128x or 256x)
> 
> I have 2 screenshots. Both have the f3 menu open. The first one is WITHOUT Lazydfu installed and the second is WITH Lazydfu installed
> ![LazyDfu NOT INSTALLED](https://user-images.githubusercontent.com/86382621/123339012-70e1bd00-d50f-11eb-924a-00ab5251f0a8.png)
> ![LazyDfu INSTALLED](https://user-images.githubusercontent.com/86382621/123339020-750dda80-d50f-11eb-9a20-c993f211f7fe.png)

The allocated memory can be set by Xms, https://stackoverflow.com/questions/1565388/increase-heap-size-in-java

**Comment by DragonEggBedrockBreaking** [comment]
> Because I want minecraft to USE the ram I ALLOW it to USE

Minecraft cannot magically just put more things in RAM, that’s not how it works. You allocate the max memory, and then based on the code, it will allocate stuff to RAM. Honestly, allocating anything over 4gb at all is overkill and is just a waste of performance, because Minecraft using it means that there is some serious issue somewhere.

**Comment by DragonEggBedrockBreaking** [comment]
> Also stuttering, lot's of it

Ah, now the issue is clear. Are you on an old world that has chunks not yet updated from a previous version? If you do (or are not sure), try running “optimise world” on your world to update the chunks

**Comment by Lucario4LyfeYT** [comment]
> > Also stuttering, lot's of it
> 
> Ah, now the issue is clear. Are you on an old world that has chunks not yet updated from a previous version? If you do (or are not sure), try running “optimise world” on your world to update the chunks

No, I made the world without the lazydfu mod installed and then went onto the lazydfu mod

**Comment by DragonEggBedrockBreaking** [comment]
Could you demonstrate this stuttering by pressing alt + f3 (to show graphs), and posting a screenshot here (both with and without lazydfu)

**Comment by Lucario4LyfeYT** [comment]
I can

**Comment by Lucario4LyfeYT** [comment]
The graph isn't showing up for me, are there other key combinations or is [alt] + f3 the only one?

**Comment by DragonEggBedrockBreaking** [comment]
Are you on a laptop?

**Comment by Lucario4LyfeYT** [comment]
desktop, whenever I press [alt] + f3, an nvidia thing pops up, but no graph

**Comment by DragonEggBedrockBreaking** [comment]
I believe that is some kind of nvidia software hotkey, yes

**Comment by Lucario4LyfeYT** [comment]
Nevermind I had to press shift with [alt]+ f3

**Comment by DragonEggBedrockBreaking** [comment]
Shift also opens a pie chart btw, but since it doesn’t cover the left FPS graph, it should be fine

**Comment by Lucario4LyfeYT** [comment]
> Shift also opens a pie chart btw, but since it doesn’t cover the left FPS graph, it should be fine

![Lazydfu installed](https://user-images.githubusercontent.com/86382621/123340982-cc617a00-d512-11eb-8458-0f69fdead776.png)
![Lazydfu not installed](https://user-images.githubusercontent.com/86382621/123340988-cec3d400-d512-11eb-9211-2940b1634452.png)


First is with Lazydfu, second is without

**Comment by Lucario4LyfeYT** [comment]
I walked around in new chunks for both demonstrations

**Comment by DragonEggBedrockBreaking** [comment]
So the main issue here is that you are getting FPS stuttering? You should open a new issue for that then (due to this one being full of comments about a non-existent RAM issue that may or may not be unrelated)

**Comment by Lucario4LyfeYT** [comment]
> So the main issue here is that you are getting FPS stuttering? You should open a new issue for that then (due to this one being full of comments about a non-existent RAM issue that may or may not be unrelated)

I'm sorry if I caused you any problems, but the ram issue is still there, it rarely goes up, out of the 20 times I tested with and without the mod installed, it only went up to 5gb max 3 times, after sitting at 2gb for about 2 - 5 min max. I don't know what is happening, but I'd call that an issue. Also yes I will start a new thread about that.

**Comment by DragonEggBedrockBreaking** [comment]
> I'm sorry if I caused you any problems, but the ram issue is still there, it rarely goes up, out of the 20 times I tested with and without the mod installed, it only went up to 5gb max 3 times, after sitting at 2gb for about 2 - 5 min max. I don't know what is happening, but I'd call that an issue. Also yes I will start a new thread about that.

Less RAM usage is a good thing not an issue. Using more RAM in game will not magically get you more performance and can actually be detrimental, so you shouldn’t be trying to allocate more RAM randomly. Maybe you could mod the game to put more things I RAM but that is probably not the best idea. There are even two mods that aim to *reduce* RAM usage, backing up my point (Hydrogan and FerriteCore).

The real problem is why does your RAM usage go to 5gb or even 9gb in vanilla in the first place, without any heavy mod packs or high res resource packs? That seems like some kind of memory leak or smth that probably needs to be fixed.

**Comment by Lucario4LyfeYT** [comment]
I use 12gb of ram in minecraft because I can, and I noticed with your mod installed it wasn't using the ram I wanted it to use, and it stuttered alot, so I found where you guys posted this mod, made a new account, and filed an issue for you guys, only to be shut down almost immediately. Also minecraft uses EVERY bit of ram it has access to, minecraft will use up to what it can use then go back down to 1gb or 3gb of ram, then rise and go down, that's what I noticed

**Comment by astei** [comment]
If you want MInecraft to use every bit of heap memory you want to give it, then set `-Xmx` equal to `-Xms`. At this point, I don't see how this discussion gets more productive since it's going around in circles. There is no issue in LazyDFU here, so I'm locking this issue.
