### ISSUE TITLE
1.17.1 Compatible?

### ISSUE THREAD

**Issue by NovaPixell** [astei/lazydfu#14]

**Comment by RDKRACZ** [comment]
As can be seen on the curseforge page, it's marked as compatible and works so what about this issue?

**Comment by astei** [comment]
As stated by me in the official release announcement on my Discord and on the mod's pages on CurseForge and Modrinth, this mod is already compatible with 1.17.1.

**Comment by NovaPixell** [comment]
I mean, the Forge version

**Comment by RDKRACZ** [comment]
There is no Forge for 1.17 yet and you already asked CorgiTaco for the Forge version.

**Comment by astei** [comment]
Guess what, this is the original version, made for Fabric. I do not make a version of this mod for Forge.
