### ISSUE TITLE
Update Modrinth and Curseforge version compatibility for 1.18

### ISSUE THREAD

**Issue by HybridEidolon** [astei/lazydfu#17]
I just tested the existing 0.1.2 jar on 1.18-pre8, and it works perfectly. Probably to be expected for such a simple mod, but that won't be obvious to players just downloading from mod hubs, so maybe Modrinth and Curseforge should be updated to indicate 1.18 compatibility when that launches.

**Comment by astei** [comment]
I will update the compatibility when they're out and not a moment sooner.
