### ISSUE TITLE
Why exactly does this work?

### ISSUE THREAD

**Issue by mainrs** [astei/lazydfu#18]
I've tried to poke a little bit around but do not fully understand why this works. Beforehand, did MC compile all transformation rules, regardless of a world needing them or not? And how does setting the executor to `void` solve this? Is this _just_ the pre-game one that compiles them?

**Comment by astei** [comment]
> Beforehand, did MC compile all transformation rules, regardless of a world needing them or not?

Yes.

> And how does setting the executor to `void` solve this? 

Well, it doesn't set it to "void". It just doesn't execute the pre-caching tasks. Since these tasks are executed in a thread pool with a good chunk of system resources allocated to it, it tends to make game startup faster, especially on low-end hardware.
