### ISSUE TITLE
1.18.2 port?

### ISSUE THREAD

**Issue by itsdinkd** [astei/lazydfu#20]
will there be one?

**Comment by NoComment1105** [comment]
LazyDFU already supports 1.18.2

**Comment by astei** [comment]
Just to be clear, LazyDFU works unmodified on Minecraft 1.18.2. No release is forthcoming.

However, Minecraft 1.19 _will_ break LazyDFU. However, I've already updated LazyDFU for 1.19, so there will be a release for 1.19.
