### ISSUE TITLE
Not working in 1.19 (Pre-1, Pre-2)

### ISSUE THREAD

**Issue by Felix14-v2** [astei/lazydfu#21]
DataFixerUpper still working during the game launch and loads CPU after it.
[latest.log](https://github.com/astei/lazydfu/files/8756544/latest.log)
[crash-2022-05-23_19.37.43-client.txt](https://github.com/astei/lazydfu/files/8756582/crash-2022-05-23_19.37.43-client.txt)

**Comment by astei** [comment]
This issue is already known and I already have a version that will work with Minecraft 1.19 made. It will be released when 1.19 is released.

**Comment by Felix14-v2** [comment]
@astei , sorry to bother you, but it doesn't look like LazyDFU is working well on 1.19. The average startup time of MC 1.19 with only LazyDFU on my laptop is 1m 10s, while 1.18, together with more than 150 mods, starts in about 30s (≈15s only LazyDFU). Is it really no longer possible to optimize the launch of the game as well as it was before?

**Comment by astei** [comment]
It works for me. Something is clearly wrong on your end, or maybe Mojang has simply made the game heavier (and both are probably true). If the game logs report "Building optimized datafixer" then something is forcing the "optimized" datafixer to get built.
