### ISSUE TITLE
Does the mod do anything when installed on the server side?

### ISSUE THREAD

**Issue by muluffel** [astei/lazydfu#22]
Hey there,
Does the mod do anything when installed on the server side? Or is it just client side?
I saw the "question" label so I thought I am gonna ask here.

**Comment by astei** [comment]
Please read the wiki. The answer is yes.

**Comment by cadenkriese** [comment]
Has this changed for 1.19? I see the patch note `Mojang now (by default) does not build datafixer rules on servers. LazyDFU continues to work as usual on the client and ensures that datafixer rules will not be built on the server, for consistency.` but I'm not sure if the mod does more than this.

**Comment by astei** [comment]
The server is just doing what LazyDFU does by default now. The mod does literally nothing else.
