### ISSUE TITLE
Crash in 1.19 with OBS

### ISSUE THREAD

**Issue by Letimaki** [astei/lazydfu#23]
Minecraft crashed when I tried to record it with OBS 27.2.4 (Game capture: Specific window)

**Comment by solonovamax** [comment]
H o w

They are COMPLETELY seperate things and do nothing REMOTELY similar.

Send logs.

**Comment by astei** [comment]
This seems extremely unlikely to be caused by LazyDFU. Send some logs.

**Comment by Letimaki** [comment]
Hmmm, it seems to be working now. Sorry for wasting your time
