### ISSUE TITLE
Changing from 0.1.1 to 0.1.2 crashes on Startup

### ISSUE THREAD

**Issue by Helper006** [astei/lazydfu#5]
I am using Java 15 to run Fabric for Minecraft 1.16.5. Before the loading screen is even loaded, the game will crash. By reverting to DFU 0.1.1, it fixes the issue. 

Mods used: 
![image](https://user-images.githubusercontent.com/33707404/108606296-fba68580-737e-11eb-82c6-7fcd219062e3.png)

![image](https://user-images.githubusercontent.com/33707404/108606303-06f9b100-737f-11eb-83bc-35dacf450978.png)

**Comment by astei** [comment]
Unable to reproduce
